# Generated by Django 3.1.7 on 2021-03-24 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_carro', models.CharField(max_length=100)),
                ('modelo_carro', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=10)),
                ('cor', models.CharField(max_length=15)),
                ('chassi', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=200)),
                ('cpf', models.IntegerField()),
                ('contato', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('Carros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aluguel.carros')),
                ('Clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aluguel.clientes')),
            ],
        ),
    ]
