# Generated by Django 3.1.7 on 2021-03-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aluguel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='data_retorno',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='data_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
