# Generated by Django 3.1.7 on 2021-03-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aluguel', '0002_auto_20210324_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='contato',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(max_length=20),
        ),
    ]
