# Generated by Django 3.1.7 on 2021-03-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aluguel', '0003_auto_20210325_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carros',
            options={'verbose_name': 'Carro', 'verbose_name_plural': 'Carros'},
        ),
        migrations.RenameField(
            model_name='carros',
            old_name='marca_carro',
            new_name='carro',
        ),
        migrations.RemoveField(
            model_name='carros',
            name='modelo_carro',
        ),
        migrations.AlterField(
            model_name='carros',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
