# Generated by Django 3.1.7 on 2021-03-29 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aluguel', '0004_auto_20210329_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluguel',
            old_name='Carros',
            new_name='carro',
        ),
        migrations.RenameField(
            model_name='aluguel',
            old_name='Clientes',
            new_name='cliente',
        ),
    ]
