# Generated by Django 3.1.7 on 2021-04-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aluguel', '0006_auto_20210401_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
